version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coffee_membership_backend
    restart: always
    ports:
      - "${PORT:-5050}:${PORT:-5050}"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
